import React from "react";
import styled from "styled-components/macro";

const Container = styled.article`
`;

const Title = styled.h1`
	margin: 0;
	padding-top: 50px;
`;

const SubTitle = styled.h2``;

const Text = styled.p``;

function About () {
	return (
		<Container>
			<Title>Heart of a storm</Title>
			<Text>{"A powerhouse to be reckoned with in the intellectual space of Kerala, Balakrishnan was an author par excellence, a committed and daring journalist, a fiery orator and above all a great human being.He authored one of best and most widely read novels of the language,a controversial and original history of the state,and a series of studies unparalleled in their depth and understanding of the subject and originality of vision.He never took the beaten tracks in whatever he did. His vision and learning took him through unchartered territories which he conquered with his characteristic mastery."}</Text>
			<SubTitle>Childhood</SubTitle>
			<Text>{"Edavanakkaad - that is the name of the beautiful village in Vypeen island off the coast of Ernakulam where Balakrishnan was born to Kesavan Asan and Mani in a middle class family. The youngest after three daughters, he had the pride of place in the family. His sisters were Janaki, Lakshmi and Parvathi. Nearest to him in age, he recalls Parvathy as his naughty sister constantly reporting on him and earning him frequent taste of the rod. He used to recall ruefully that after appreciating as ‘the great goat’, the dog he had made, she was instrumental in him being caught red handed while trying to taste the baked clay figure. With years his area of activity extended to the neighbourhood and then beyond with his cousins Sekharan, Chennan and Kesavan"}.</Text>
			<Text>{"Edavanakkad, with its rustic beauty and winding country paths and canals were far away from development. It was accessible by boat only. The luxury carrier, the cycle came only later. His sister Parvathy remembers the grand spectacle of elephant crossing the canals that only had logs for people to cross. The elephants had to enter the canal and wade through amidst a big gathering watching and hooting. The child hood flavours of this beautiful village can be caught in his novel ‘Pluto’."}</Text>
			<Text>{"Balakrishnan was an outstanding student. His studies were not neglected even after his father was bedridden with paralysis. He passed school with a gold medal and went on to study in college which was the normal route of the financially affluent."}</Text>
			<SubTitle>Balakrishnan The Student</SubTitle>	
			<Text>{"He learnt his first letters writing on the sand spread out at Madhavan Aashan’s Kalari (Kalari is where learning started in olden days under the guidance of an Aashan= teacher). However the little student dropped out soon scared of the drunken teacher. His learning continued through the Sanmarga Pradeepika Sabha (SPS Primary)School, Lower Secondary School, and finally The Rama Varma Union High school (1940) in the neighbouring village of Cherai. His oratorical skills developed during this period. He was actively encouraged by his teachers. The headmaster K.C.Abraham or Abraham master (who later served as governor of Andhra Pradesh) and Alexander, the Malayalam teacher were tutors here with whom he maintained contacts and whom he remembered with great respect. He also read extensively on a level that far exceeded his age. He passed out of school with a gold medal and a scholarship for higher studies."}</Text>
			<Text>{"He shifted to Ernakulam and joined the Maharajas College for his higher studies. He selected science as his subject as he was told that it was the most difficult to study. He was very active in college. However, academic studies were last in his agenda. It was the time when the freedom movement had gathered momentum and there was no way the energetic youth could keep out. He whole-heartedly jumped into it. The involvement in quit India movement ended in jail. He used to say in private that the stay in jail as a class B detinue together with the sons of influential persons would have been enjoyable if only he could make his weekend trips home (it was his unfailing habit).Thus, his four eventful years in college ended without any qualification degree."}</Text>
			<SubTitle>Man of Letters</SubTitle>
			<Text>{"Balakrishnan was a prolific writer from his student days. But practically little of what he wrote has survived. His recorded journey as an author starts from the anthology ‘Narayana ‘Guru’, a comprehensive work on the great reformer and spiritual leader of Kerala. The book also amply demonstrates the intellectual depth and vast understanding that Balakrishanan who would have been hardly 23 years at the time had. Most of Balakrishnan’s works are critical works. His studies on Chandu Menon (the first widely accepted Malayali novelist), the art of poetry through Kumaran Asan (the doyen of Malayalam literature) Vyasa Bharatha & Ezhuthachan (the father of Malayalam poetry) and the art of the novel are unparallel works that enriched critical literature."}</Text>
			<Text>{"An avid reader, history was his favourite. As part of his wide reading, Kerala history naturally found a special place. He found that there was a disconnect between what the existing popular history sought to project, and what he saw of Kerala from the old literature, travelogues, and other first hand sources that is used to study history. In his writings he first dealt with Kerala history in the anthology ‘Narayana Guru’, the great social reformer of Kerala who changed the face of its caste ridden society. To fully comprehend the greatness of the man and the work he did, the history of Kerala in the 18th and 19th centuries are studied as a back drop. He brushes with Kerala history again to study why Tipu Sultan, an able ruler and administrator is only perceived as an aggressor and religious fanatic in our writings. The culmination of these studies over 3 decades was his work on the social history ‘Jaathivyavasthayum Kerala Charitravum’ (The Caste System and History of Kerala). The book created a furor in the ‘historical circles’ and generated widespread interest and discussion on Kerala history. The unrealistic and imaginative flourishes that were passed off as history were debunked with this single work. The people and their history were studied within the reality frame work of the caste system, agriculture, commerce, administrative set up etc. It is a seminal work that deals with various aspects of Kerala’s history including the development of the Malayalam language. "}</Text>
			<Text>{"However what catapulted him as a popular writer was his second novel ‘Ini Njan Urangatte’ (And Now Let Me Sleep). The novel is the story of Karna through the eyes of Draupadi. A work originating from the Mahabharatha, it has caught the stylised language and mood of the great epic. It maintains the original story, epic atmosphere, events and characters which distinguishes it from other works based on Mahabharatha The book is unparalleled in its lofty language, imagery and depth and is considered one of the best classics in Indian Literature. English, Tamil and Kannada translations of this novel have been brought out by Kendra Sahitya Akademi. The novel won him the Kerala Sahitya Akademi Award, Sahitya Pravarthaka Benefit Fund Award and the prestigious Vayalar Award given in honour of the poet Vayalar Rama Varma,who was immortalised in Malayalam cinema by his beautiful lyrics."}</Text>
			<Text>{"‘Ini Njan Urangatte’ was quite a departure from his first novel ‘Pluto’ the story of his dog. Set in the back drop of his native village of Edavanakkad, it provides a glimpse of his friends and relatives. While his extensive interests resulted in full fledged books, his numerous other interests resulted in various articles. No serious attempts were made to preserve the articles he wrote. So, many of these were lost after their first publication. Some of these were complied and published in his life time ‘Mayatha Sandhyakal’ (Unfading Twilights) and ‘Nidra Sancharangal’ (Sleep Walkings). These were combined and brought out as Balakrishnante Lekhanangal (Articles of Balakrishnan) in 2005. A subsequent collection of articles were published as ‘Keraleeyathayum Mattum’ (The Essence of Kerala etc) and Veritta Chintakal (Thoughts Apart). Some of his hitherto unpublished writings were compiled by Hashim Rajan in his special Kaumudi edition in 2012. As on date Balakrishnan has 12 published books to his credit."}</Text>
			<SubTitle>Major Influences in His Life</SubTitle>
			<Text>{"Extremely intelligent with a sound reading habit, getting into politics was only a logical progression given the tumultuous times he was in. He caught attention with his writings and oratorical skills. He came into contact with many like-minded and eminent persons. Though his essay into politics came to naught, this was a formative period of his life. The well-known social activist Sahodaran Ayyappan was a benevolent influence on his life. The credit for Balakrishnan's first work, an anthology, goes to him. "}</Text>
			<Text>{"He took over the bookshop called 'Circle Book House' at Eranakulam boat jetty run by Vaikkom Muhammed Bashir(the well known Malayalam writer) and managed it for nearly 6 years till 1958. His skill with language soon saw to it that the bookshop was stocked with books from many well-known publishers and literary creations published from all over the world. He subscribed the best magazines at that time,' Encounter' being one of them. It will be needless to mention that his skill as a salesman was exceeded by his interest in reading the excellent books at hand. An avid reader, this provided him with a wonderful opportunity to do what he liked."}</Text>
			<SubTitle>Brief Political Encounters in His Life </SubTitle>
			<Text>{"His voracious reading habit had already created a high degree of political awareness in Balakrishnan. Reading through the numerous volumes of history of the Indian National Congress and a close watch of the political activities around him had invigorated him to join the main stream political movement of the time. Participation in the quit India movement landed him in jail. It was in prison that he first met people like C.Achutha Menon and K.Karunakaran (both were to become Chief Ministers later) who were serving their jail term as political prisoners. "}</Text>
			<Text>{"He then spent a few years as full time member of Prajamandalam, the Congress unit of Cochin State which later split and formed the Kerala Socialist Party under Mathai Manjoornan. He had strong convictions and he stood by his beliefs. He soon found that these were not sound 'political' qualities and finding politics unfit for him and himself unfit for politics, literally ran away from it at the middle of the night with his meager belongings tucked under his arm. The net result of all this was a ruined academic future. He put to full use his capabilities as an orator and writer during this period of political activity. He was the force behind the weekly 'Azad', the mouthpiece of the student Congress started in 1947. Later he edited the weekly of the Kerala Socialist party - 'Socialist'. He wrote innumerable political articles during this period in these and many other publications. He had established his reputation as a writer by this time."}</Text>
		</Container>);
}

export default About;