name: Deploy to GitHub Pages

on:
  push:
    branches:
      - github-deploy-action  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Deploy React App
        run: |
          git config user.name "GitHub Actions"
          git config user.email "zi.avi7@gmail.com"
          npm run deploy
